// src/routes/decks/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { useMachine } from '@xstate/svelte';
	import { deckMachine } from '$lib/state/deckMachine';
	import { PlusCircle, Trash2, Edit3, Play } from 'lucide-svelte';
	import Button from '$components/ui/button/Button.svelte';
	import Card from '$components/ui/card/Card.svelte';
	import CardContent from '$components/ui/card/CardContent.svelte';
	import CardDescription from '$components/ui/card/CardDescription.svelte';
	import CardFooter from '$components/ui/card/CardFooter.svelte';
	import CardHeader from '$components/ui/card/CardHeader.svelte';
	import CardTitle from '$components/ui/card/CardTitle.svelte';

	const { snapshot, send } = useMachine(deckMachine);

	let isMounted = false;

	onMount(() => {
		isMounted = true;
		send({ type: 'LOAD_DECKS' });
	});

	function handleCreateNewDeck() {
		goto('/decks/create');
	}

	function handleEditDeck(deckId: string) {
		goto(`/decks/edit/${deckId}`);
	}

	function handlePlayGame(deckId: string) {
		goto(`/play/${deckId}`);
	}

	function handleDeleteDeck(deckId: string) {
		send({ type: 'DELETE_DECK', deckId });
	}

	// Computed deck list items
	$: deckListItems = $snapshot.context.decks
		.map(deck => ({
			id: deck.id,
			name: deck.name,
			cardCount: deck.cards.reduce((sum, card) => sum + card.quantity, 0),
			updatedAt: deck.updatedAt,
			format: 'Classic' // Default format for now
		}))
		.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
</script>

<svelte:head>
	<title>Deck Builder - AlterDeck</title>
	<meta name="description" content="Create, manage, and refine your Altered TCG decks" />
</svelte:head>

<div class="space-y-8">
	<section class="flex flex-col sm:flex-row justify-between items-center gap-4">
		<div>
			<h1 class="font-headline text-4xl font-bold tracking-tight sm:text-5xl text-primary">
				Deck Builder
			</h1>
			<p class="mt-2 text-lg text-muted-foreground">
				Create, manage, and refine your Altered TCG decks.
			</p>
		</div>
		<Button 
			on:click={handleCreateNewDeck} 
			class="bg-accent text-accent-foreground hover:bg-accent/90"
		>
			<PlusCircle class="mr-2 h-5 w-5" /> Create New Deck
		</Button>
	</section>

	{#if !isMounted || $snapshot.context.isLoading}
		<div class="text-center p-10">Loading decks...</div>
	{:else if deckListItems.length === 0}
		<Card class="text-center py-12 shadow-lg">
			<CardHeader>
				<CardTitle class="text-2xl text-muted-foreground">No Decks Yet</CardTitle>
			</CardHeader>
			<CardContent>
				<p>Start building your first deck to see it here.</p>
				<Button 
					on:click={handleCreateNewDeck} 
					variant="outline" 
					class="mt-6 border-primary text-primary hover:bg-primary/10"
				>
					Create Your First Deck
				</Button>
			</CardContent>
		</Card>
	{:else}
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
			{#each deckListItems as deck (deck.id)}
				<Card class="flex flex-col shadow-lg hover:shadow-primary/30 transition-shadow duration-300">
					<CardHeader>
						<div class="flex justify-between items-start">
							<div>
								<CardTitle class="font-headline text-xl">{deck.name}</CardTitle>
								<CardDescription>{deck.cardCount} cards - Format: {deck.format}</CardDescription>
							</div>
						</div>
					</CardHeader>
					<CardContent class="flex-grow">
						<p class="text-xs text-muted-foreground">
							Last updated: {new Date(deck.updatedAt).toLocaleDateString()}
						</p>
					</CardContent>
					<CardFooter class="flex justify-end gap-2">
						<Button 
							on:click={() => handlePlayGame(deck.id)} 
							variant="default" 
							size="sm" 
							class="bg-primary text-primary-foreground hover:bg-primary/90"
						>
							<Play class="mr-1 h-4 w-4" /> Play
						</Button>
						<Button on:click={() => handleEditDeck(deck.id)} variant="outline" size="sm">
							<Edit3 class="mr-1 h-4 w-4" /> Edit
						</Button>
						<Button 
							on:click={() => {
								if (confirm(`Are you sure you want to delete "${deck.name}"? This action cannot be undone.`)) {
									handleDeleteDeck(deck.id);
								}
							}} 
							variant="destructive" 
							size="sm"
						>
							<Trash2 class="mr-1 h-4 w-4" /> Delete
						</Button>
					</CardFooter>
				</Card>
			{/each}
		</div>
	{/if}

	<!-- Error State -->
	{#if $snapshot.context.error}
		<div class="bg-destructive/10 border border-destructive/20 rounded-lg p-4 text-destructive">
			{$snapshot.context.error}
		</div>
	{/if}
</div>

// src/app/decks/page.tsx

'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { PlusCircle, Trash2, Edit3, Play } from 'lucide-react'; // Added Play icon
import type { Deck, DeckListItem } from '@/types';
import useLocalStorage from '@/hooks/useLocalStorage';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import Image from 'next/image';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

const DECK_STORAGE_KEY = 'alterdeck-decks';

export default function DeckBuilderPage() {
  const [decks, setDecks] = useLocalStorage<Deck[]>(DECK_STORAGE_KEY, []);
  const [isMounted, setIsMounted] = useState(false);
  const { toast } = useToast();
  const router = useRouter();

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const handleDeleteDeck = (deckId: string) => {
    const deckToDelete = decks.find(d => d.id === deckId);
    setDecks(decks.filter(d => d.id !== deckId));
    toast({ title: "Deck Deleted", description: `The deck "${deckToDelete?.name || 'deck'}" has been removed.` });
  };
  
  const deckListItems: DeckListItem[] = decks.map(deck => ({
    id: deck.id,
    name: deck.name,
    cardCount: deck.cards.length,
    updatedAt: deck.updatedAt,
    heroImageUrl: deck.hero?.imageUrl || deck.cards[0]?.imageUrl,
    format: deck.format || "N/A",
  })).sort((a,b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());

  const handleCreateNewDeck = () => {
    router.push('/cards?action=create');
  };

  const handleEditDeck = (deckId: string) => {
    router.push(`/cards?deckId=${deckId}`);
  };

  const handlePlayGame = (deckId: string) => {
    router.push(`/play/${deckId}`);
  };

  if (!isMounted) {
    return <div className="text-center p-10">Loading decks...</div>; 
  }

  return (
    <div className="space-y-8">
      <section className="flex flex-col sm:flex-row justify-between items-center gap-4">
        <div>
          <h1 className="font-headline text-4xl font-bold tracking-tight sm:text-5xl text-primary">Deck Builder</h1>
          <p className="mt-2 text-lg text-muted-foreground">
            Create, manage, and refine your Altered TCG decks.
          </p>
        </div>
        <Button onClick={handleCreateNewDeck} className="bg-accent text-accent-foreground hover:bg-accent/90">
          <PlusCircle className="mr-2 h-5 w-5" /> Create New Deck
        </Button>
      </section>

      {deckListItems.length === 0 ? (
        <Card className="text-center py-12 shadow-lg">
          <CardHeader>
            <CardTitle className="text-2xl text-muted-foreground">No Decks Yet</CardTitle>
          </CardHeader>
          <CardContent>
            <p>Start building your first deck to see it here.</p>
            <Button onClick={handleCreateNewDeck} variant="outline" className="mt-6 border-primary text-primary hover:bg-primary/10">
              Create Your First Deck
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {deckListItems.map((deck) => (
            <Card key={deck.id} className="flex flex-col shadow-lg hover:shadow-primary/30 transition-shadow duration-300">
              <CardHeader>
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="font-headline text-xl">{deck.name}</CardTitle>
                    <CardDescription>{deck.cardCount} cards - Format: {deck.format}</CardDescription>
                  </div>
                  {deck.heroImageUrl && (
                    <Image src={deck.heroImageUrl} alt={deck.name} width={60} height={84} className="rounded-md border border-border object-cover" data-ai-hint={deck.name.toLowerCase().split(' ').slice(0,2).join(' ')}/>
                  )}
                </div>
              </CardHeader>
              <CardContent className="flex-grow">
                <p className="text-xs text-muted-foreground">Last updated: {new Date(deck.updatedAt).toLocaleDateString()}</p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button onClick={() => handlePlayGame(deck.id)} variant="default" size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90">
                  <Play className="mr-1 h-4 w-4" /> Play
                </Button>
                <Button onClick={() => handleEditDeck(deck.id)} variant="outline" size="sm">
                  <Edit3 className="mr-1 h-4 w-4" /> Edit
                </Button>
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button variant="destructive" size="sm">
                      <Trash2 className="mr-1 h-4 w-4" /> Delete
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                      <AlertDialogDescription>
                        This action cannot be undone. This will permanently delete the deck "{deck.name}".
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>Cancel</AlertDialogCancel>
                      <AlertDialogAction onClick={() => handleDeleteDeck(deck.id)}>Delete</AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
